version: '3.8'
services:
  apartments-service:
    container_name: apartments-service
    build:
      context: .
      dockerfile: ./apps/apartments-service/Dockerfile
      target: development
    command: npx nx run apartments-service:serve
    env_file:
      - ./apps/apartments-service/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3009:3009'
  user-auth-manager:
    container_name: user-auth-manager
    build:
      context: .
      dockerfile: ./apps/user-auth-manager/Dockerfile
      target: development
    command: npx nx run user-auth-manager:serve
    env_file:
      - ./apps/user-auth-manager/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4040:4040'